### ISSUE TITLE
Limit data requests from Influx

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie#71]
Currently the Cozie website explains how to query Cozie data from Influx, however, we are not limiting the number of requests per user. This may be needed, in addition we may want to allow only registered users to be able to query data from coziePulic

**Comment by pjayathissa** [comment]
Good idea, I will explore options if the medical cozie goes ahead because we will need advanced security features there anyway

**Comment by pjayathissa** [comment]
Moved to cozie-gateway repo as it is a backend issue not a front end
