### ISSUE TITLE
GPS location data missing

### ISSUE THREAD

**Issue by FedericoTartarini** [buds-lab/cozie#74]
I have set up the Cozie App on many participants devices using the same methodology, however, I have noticed that for the great majority of Android users, the Cozie app has some issues and it is not sending the GPS location.

All participants have enabled location, on their phone and allowed the Cozie clock face to get location data, however, I am still not receiving any information regarding their position. As you can see from the file attached below the great majority of the data are missing. The strange behavior is that for example participant "dorn03" (Android user) sometimes sends his/her location while sometimes the location comes in as NaN. Obviously the app is also not sending the longitude data, however, I have omitted this data to ensure that participants could not be identified.

![image](https://user-images.githubusercontent.com/40018640/79522321-f2c59300-808d-11ea-930a-13020b72caea.png)

**Comment by FedericoTartarini** [comment]
[In this repository](https://github.com/joeledwards/iso-plus/blob/location/app/index.js) they are using the following code. The author claims their code is working! I have not tested that, but they use a setTimeout inside both the locationSuccess and locationError function. 

```
function checkLocation() {
  let start = Date.now();
  geolocation.getCurrentPosition(
    reading => {
      geoReport(reading);
      setTimeout(checkLocation, 1000);
    },
    error => {
      geoError(error);
      setTimeout(checkLocation, 1000);
    }
  )
}
```

While we have specified the timeout inside the getCurrentPosition function as follows. Our approach seems to be correct, see [original documentation here](https://dev.fitbit.com/build/guides/geolocation/).
```
geolocation.getCurrentPosition(locationSuccess, locationError, {timeout: 30000, maximumAge: 120000});

function locationSuccess(position) {
        console.log("location success");
        feedbackData.lat = position.coords.latitude;
        feedbackData.lon = position.coords.longitude;
        sendDataToCompanion(feedbackData);
    }
```

Finally another reason for this problem is that in these days "Lock down" people are most likely completing the survey indoors where their GPS may not be working well, consequently that could be the cause of the error.

**Comment by FedericoTartarini** [comment]
Actually please ignore the last comment about the fact that the issue could be caused by the fact that people are indoor since that is incorrect. For example a user completed three times the survey in front of me while indoor in within 10 minutes from the same location, however, I received the GPS data only once.

**Comment by FedericoTartarini** [comment]
Or actually the fact that the user is indoor could in-fact be the issue. Since they state:

Note: GPS does not work well indoors. You will only receive the success callback when a 3D-fix is obtained, this may require up to 4 satellites.

Even though it is strange that some users never got a GPS fix over the last few weeks

**Comment by FedericoTartarini** [comment]
I have increased the timeout to 4 minutes for the function getCurrentPosition and this change seems to help. I will test it over the course of the weekend and see if this fixes the problem

```
geolocation.getCurrentPosition(locationSuccess, locationError, {timeout: 4 * 60 * 1000, maximumAge: 4 * 60 * 1000});
```

**Comment by pjayathissa** [comment]
@FedericoTartarini A functionality that I wanted to introduce was a small GPS logo on the bottom right corner. It would light up when searching for GPS. When successful or fail, the watch would buzz, and the logo would be replaced by a tick or cross for a few seconds.

This may help the debugging and would be in general a nice feature to have. 

I notice on iOS that you have to give permission to the phone about three times before it finally allows GPS to always be on in background. Otherwise, the moment you leave feedback, the iPhone will prompt saying "Fitbit wants to use your location data now, do you agree", which I personally always miss. And by the time I give the ok, it has already been at least 10min, and the watch has missed the data point.
When testing on Android, I also noticed that the GPS was really unstable.

**Comment by FedericoTartarini** [comment]
Okay I can have a look into adding that visual clue, and I agree it is a nice feature. However, it will not unfortunately help the participant in taking any actions that could practically solve the issue. This could at the same time make them more confused.

**Comment by pjayathissa** [comment]
Another option, if GPS is really important, we could consider getting Ionic watches on the next round of purchases. Perhaps something to keep @cmiller8 in the loop about
